server:
    port: 8083

spring:
    application:
      name: order-service
    datasource:
      url: jdbc:postgresql://localhost:5434/orderdb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.driver
    flyway:enable: true
    location: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true


user:
  service:
    url: http://localhost:8081

product:
  service:
    url: http://localhost:8082